name: d_py310_pv3
dependencies:
    - python=3.10
    - jupyter
    - matplotlib
    - pandas
    - plotly
    - sqlalchemy
    - seaborn
    - xlrd
    - openpyxl
    - psycopg2
    - pip:
        - pvlib
