name: d_py314_pv3
dependencies:
    - python=3.14
    - jupyter
    - matplotlib
    - pandas
    - plotly
    - sqlalchemy
    - seaborn
    - xlrd
    - openpyxl
    - psycopg2
    - pip:
        - pvlib
